#!/usr/bin/env ruby

PENDING=2
NO_STATUS=3
GITHUB_SUCCESS="✔︎"
GITHUB_FALURE="✖︎"
return_txt = ""

project_name = `basename $(git rev-parse --show-toplevel)`

test_name_regex = ARGV[0] || ".*"

def test_complete(parsed_line)
  [GITHUB_SUCCESS, GITHUB_FALURE].include?(parsed_line[0])
end

status_rows = []

loop do
  return_txt = `hub ci-status -v`
  status_rows = return_txt.split("\n").map{ |l| l.split("\t", 3).map{ |s| s.strip} }
  break if status_rows.select{ |l| /#{test_name_regex}/.match(l[1]) }.all?{|row| test_complete(row)}
  sleep(1)
end

def notify(status_txt, title, url_args)
    system("terminal-notifier -message 'Build #{status_txt}' -title '#{title}' #{url_args}")
end


rows_by_status = status_rows.select{ |l| /#{test_name_regex}/.match(l[1]) }.group_by{ |l| l[0] }

if rows_by_status[GITHUB_FALURE].nil?
    # success
    notify(GITHUB_SUCCESS, project_name, '')
else
    rows_by_status[GITHUB_FALURE].each do |fail,test_name,test_url|
        notify(GITHUB_FALURE, test_name, "-open #{test_url}")
    end
end
